### 
POST https://prueba-videollamada-back.vercel.app/insert-room HTTP/1.1
content-type: application/json

{
 "user": "xa", 
 "roomId": "bsdfsdfsdfsdfds",
 "date": "23423432"
}

###

GET  http://localhost:1234/get-rooms HTTP/1.1
content-type: application/json

 
###

GET  https://prueba-videollamada-back.vercel.app/get-rooms HTTP/1.1
content-type: application/json

 
###
 